# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: demo.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ndemo.proto\x12\x04\x64\x65mo\"\x07\n\x05\x45mpty\"S\n\x07Product\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x63\x61tegory\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x05\x12\r\n\x05image\x18\x05 \x01(\t\".\n\x0bProductList\x12\x1f\n\x08products\x18\x01 \x03(\x0b\x32\r.demo.Product\" \n\x0ePaymentRequest\x12\x0e\n\x06\x61mount\x18\x01 \x01(\x05\"!\n\x0fPaymentResponse\x12\x0e\n\x06status\x18\x01 \x01(\t2@\n\x0eProductService\x12.\n\x0cListProducts\x12\x0b.demo.Empty\x1a\x11.demo.ProductList2G\n\x0ePaymentService\x12\x35\n\x06\x43harge\x12\x14.demo.PaymentRequest\x1a\x15.demo.PaymentResponseB\'Z%../src/product-service;productserviceb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'demo_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z%../src/product-service;productservice'
  _globals['_EMPTY']._serialized_start=20
  _globals['_EMPTY']._serialized_end=27
  _globals['_PRODUCT']._serialized_start=29
  _globals['_PRODUCT']._serialized_end=112
  _globals['_PRODUCTLIST']._serialized_start=114
  _globals['_PRODUCTLIST']._serialized_end=160
  _globals['_PAYMENTREQUEST']._serialized_start=162
  _globals['_PAYMENTREQUEST']._serialized_end=194
  _globals['_PAYMENTRESPONSE']._serialized_start=196
  _globals['_PAYMENTRESPONSE']._serialized_end=229
  _globals['_PRODUCTSERVICE']._serialized_start=231
  _globals['_PRODUCTSERVICE']._serialized_end=295
  _globals['_PAYMENTSERVICE']._serialized_start=297
  _globals['_PAYMENTSERVICE']._serialized_end=368
# @@protoc_insertion_point(module_scope)
