name: api gateway CI

on:
  push:
    branches: [ "main" ]
    paths: [ "src/api-gateway/**" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yaml
    with:
      service-name: api-gateway
      service-path: src/api-gateway
      k8s-manifest: k8s/api-gateway.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
