name: frontend CI

on:
  push:
    branches: [ "main" ]
    paths: [ "src/frontend/**" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy-template.yaml
    with:
      service-name: frontend
      service-path: src/frontend
      k8s-manifest: k8s/frontend.yaml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
